users: dGVzdHVzZXI6JDJhJDEwJEtIMTZMV1lFa0xGQ21TdjFCbjdjTGVTbUw1Ri5wQmhGWW11c1JGMXNZYUNIcmhnTlFXSlZXCg==
user_roles: dmlld2VyOnRlc3R1c2VyCg==

elastic:
  resources:
    requests:
      memory: 4Gi
      cpu: 50m
    limits:
      memory: 4Gi
      cpu: 4
  storage: '10Gi'

exporter:
  extraEnvSecrets:
    ES_PASSWORD:
      secret: lv-prod-comment-api-v2-es-elastic-user
  es: # Must be http://{{ .Release.name }}-es-http:9200 where release.name = argoApplication name
    uri: http://lv-prod-comment-api-v2.kibana.delfi.lv-es-http:9200
